name: bhavaniconnect
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #provider: ^4.0.0
  flutter_offline: ^0.3.0

  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  firebase_core: ^0.4.4+3

  simple_animations: ^1.3.9
  image_picker: ^0.6.4
  image_cropper: ^1.2.1
  url_launcher: ^5.1.2
  intl: ^0.16.1
  flutter_form_builder: ^3.8.0+1
  percent_indicator: ^2.1.1+1
  flutter_animation_progress_bar: ^1.0.0
  flappy_search_bar: ^1.4.1
  flutter_launcher_icons: 0.7.4
  shimmer: ^1.1.0
  grouped_buttons: ^1.0.4
  flutter_cupertino_date_picker: ^1.0.12
  dropdownfield: ^1.0.3
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  location: ^2.5.4
  #  flutter_open_whatsapp: ^0.1.2
  auto_size_text: ^2.1.0
  notification_permissions: ^0.4.4
  spring_button: ^1.0.13
  calendar_timeline: 0.4.0
  dropdown_formfield: 0.1.2
  dropdown_search: 0.3.3
  flutter_slidable: 0.5.4
  slide_to_confirm: 0.0.6
  toast:
  path_provider: ^1.6.9
  firebase_messaging: ^6.0.16
  device_info: ^0.4.2+4
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.7+3
  latlong: ^0.6.1
  # excel: ^1.0.8
  csv: ^4.0.3
  share_extend: ^1.1.5
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/22.JPG"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-SemiBold.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/22.JPG
    - images/1.JPG
    - profile_image.jpg
    - images/bill.jpg
    - images/lorry.jpg
    - images/whatsapp.png
    - images/splash1.jpg
    - images/splash2.jpg
    - images/splash3.jpg
    - images/no_internet.png
    - images/done.png
    - images/Addstock.jpg
    - images/Approval.jpg
    - images/Attendance.jpg
    - images/construction.png
    - images/inventory.png
    - images/ManageEmployees.jpg
    - images/store.jpg
    - images/jcb.png
    - images/c1.png
    - images/c2.png
    - images/c3.png
    - images/c4.png
    - images/c5.png
    - images/c6.png
    - images/c7.png
    - images/c8.png
    - images/c9.png
    - images/c10.png
    - images/c11.png
    - images/invoice.png
    - images/siteActivity.png
    - images/Concrete.png
    - images/LabourReport.png
    - images/s1.png
    - images/s2.png
    - images/s3.png
    - images/s4.png
    - images/s5.png
    - images/s6.png
    - images/s7.png
    - images/profile.jpeg
    - images/generic_user.png
    - images/transparent.png
    - images/profile-uploading.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
